namespace SAMCS
{
    public class ReciterTabs
    {

        //some flags
        public static readonly byte[] tab36376 =
        {
            0, 0, 0, 0, 0, 0, 0, 0, // 0-7
            0, 0, 0, 0, 0, 0, 0, 0, // 8-15
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 2, 2, 2, 2, 2, 2, 130, // (byte)' ', '!'
            0, 0, 2, 2, 2, 2, 2, 2,
            3, 3, 3, 3, 3, 3, 3, 3,
            3, 3, 2, 2, 2, 2, 2, 2,
            2, 192, 168, 176, 172, 192, 160, 184, // (byte)'@', 'A'
            160, 192, 188, 160, 172, 168, 172, 192,
            160, 160, 172, 180, 164, 192, 168, 168,
            176, 192, 188, 0, 0, 0, 2, 0, // (byte)'X', (byte)'Y', (byte)'Z', (byte)'[',
            32, 32, 155, 32, 192, 185, 32, 205,
            163, 76, 138, 142
        };

        public static readonly byte[] rules =
        {
            (byte)']','A'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)'.',(byte)')',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4',(byte)'Y',(byte)'.',' '|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)' ',                        (byte)'=',(byte)'A','H'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)'R',(byte)'E',(byte)')',(byte)' ',            (byte)'=',(byte)'A',(byte)'A','R'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)'R',(byte)')',(byte)'O',                (byte)'=',(byte)'A',(byte)'X','R'|0x80,
            (byte)'(',(byte)'A',(byte)'R',(byte)')',(byte)'#',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','R'|0x80,
            (byte)' ',(byte)'^',(byte)'(',(byte)'A',(byte)'S',(byte)')',(byte)'#',            (byte)'=',(byte)'E',(byte)'Y',(byte)'4','S'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'W',(byte)'A',                    (byte)'=',(byte)'A','X'|0x80,
            (byte)'(',(byte)'A',(byte)'W',(byte)')',                        (byte)'=',(byte)'A',(byte)'O','5'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'A',(byte)'N',(byte)'Y',(byte)')',            (byte)'=',(byte)'E',(byte)'H',(byte)'4',(byte)'N',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'^',(byte)'+',(byte)'#',                (byte)'=',(byte)'E',(byte)'Y','5'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'A',(byte)'L',(byte)'L',(byte)'Y',(byte)')',        (byte)'=',(byte)'U',(byte)'L',(byte)'I','Y'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)'L',(byte)')',(byte)'#',                (byte)'=',(byte)'U','L'|0x80,
            (byte)'(',(byte)'A',(byte)'G',(byte)'A',(byte)'I',(byte)'N',(byte)')',            (byte)'=',(byte)'A',(byte)'X',(byte)'G',(byte)'E',(byte)'H',(byte)'4','N'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'A',(byte)'G',(byte)')',(byte)'E',            (byte)'=',(byte)'I',(byte)'H','J'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'^',(byte)'%',                    (byte)'=',(byte)'E','Y'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'^',(byte)'+',(byte)':',(byte)'#',            (byte)'=',(byte)'A','E'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'A',(byte)')',(byte)'^',(byte)'+',(byte)' ',        (byte)'=',(byte)'E',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)'R',(byte)'R',(byte)')',                (byte)'=',(byte)'A',(byte)'X','R'|0x80,
            (byte)'(',(byte)'A',(byte)'R',(byte)'R',(byte)')',                    (byte)'=',(byte)'A',(byte)'E',(byte)'4','R'|0x80,
            (byte)' ',(byte)'^',(byte)'(',(byte)'A',(byte)'R',(byte)')',(byte)' ',            (byte)'=',(byte)'A',(byte)'A',(byte)'5','R'|0x80,
            (byte)'(',(byte)'A',(byte)'R',(byte)')',                        (byte)'=',(byte)'A',(byte)'A',(byte)'5','R'|0x80,
            (byte)'(',(byte)'A',(byte)'I',(byte)'R',(byte)')',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','R'|0x80,
            (byte)'(',(byte)'A',(byte)'I',(byte)')',                        (byte)'=',(byte)'E',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'A',(byte)'Y',(byte)')',                        (byte)'=',(byte)'E',(byte)'Y','5'|0x80,
            (byte)'(',(byte)'A',(byte)'U',(byte)')',                        (byte)'=',(byte)'A',(byte)'O','4'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'A',(byte)'L',(byte)')',(byte)' ',            (byte)'=',(byte)'U','L'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'A',(byte)'L',(byte)'S',(byte)')',(byte)' ',        (byte)'=',(byte)'U',(byte)'L','Z'|0x80,
            (byte)'(',(byte)'A',(byte)'L',(byte)'K',(byte)')',                    (byte)'=',(byte)'A',(byte)'O',(byte)'4','K'|0x80,
            (byte)'(',(byte)'A',(byte)'L',(byte)')',(byte)'^',                    (byte)'=',(byte)'A',(byte)'O','L'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'A',(byte)'B',(byte)'L',(byte)'E',(byte)')',        (byte)'=',(byte)'E',(byte)'Y',(byte)'4',(byte)'B',(byte)'U','L'|0x80,
            (byte)'(',(byte)'A',(byte)'B',(byte)'L',(byte)'E',(byte)')',                (byte)'=',(byte)'A',(byte)'X',(byte)'B',(byte)'U','L'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'V',(byte)'O',                    (byte)'=',(byte)'E',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'A',(byte)'N',(byte)'G',(byte)')',(byte)'+',                (byte)'=',(byte)'E',(byte)'Y',(byte)'4',(byte)'N','J'|0x80,
            (byte)'(',(byte)'A',(byte)'T',(byte)'A',(byte)'R',(byte)'I',(byte)')',            (byte)'=',(byte)'A',(byte)'H',(byte)'T',(byte)'A',(byte)'A',(byte)'4',(byte)'R',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'T',(byte)'O',(byte)'M',                (byte)'=',(byte)'A','E'|0x80,
            (byte)'(',(byte)'A',(byte)')',(byte)'T',(byte)'T',(byte)'I',                (byte)'=',(byte)'A','E'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)'T',(byte)')',(byte)' ',                (byte)'=',(byte)'A',(byte)'E','T'|0x80,
            (byte)' ',(byte)'(',(byte)'A',(byte)')',(byte)'T',                    (byte)'=',(byte)'A','H'|0x80,
            (byte)'(',(byte)'A',(byte)')',                            (byte)'=',(byte)'A','E'|0x80,

            (byte)']','B'|0x80,
            (byte)' ',(byte)'(',(byte)'B',(byte)')',(byte)' ',                    (byte)'=',(byte)'B',(byte)'I',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'B',(byte)'E',(byte)')',(byte)'^',(byte)'#',            (byte)'=',(byte)'B',(byte)'I','H'|0x80,
            (byte)'(',(byte)'B',(byte)'E',(byte)'I',(byte)'N',(byte)'G',(byte)')',            (byte)'=',(byte)'B',(byte)'I',(byte)'Y',(byte)'4',(byte)'I',(byte)'H',(byte)'N','X'|0x80,
            (byte)' ',(byte)'(',(byte)'B',(byte)'O',(byte)'T',(byte)'H',(byte)')',(byte)' ',        (byte)'=',(byte)'B',(byte)'O',(byte)'W',(byte)'4',(byte)'T','H'|0x80,
            (byte)' ',(byte)'(',(byte)'B',(byte)'U',(byte)'S',(byte)')',(byte)'#',            (byte)'=',(byte)'B',(byte)'I',(byte)'H',(byte)'4','Z'|0x80,
            (byte)'(',(byte)'B',(byte)'R',(byte)'E',(byte)'A',(byte)'K',(byte)')',            (byte)'=',(byte)'B',(byte)'R',(byte)'E',(byte)'Y',(byte)'5','K'|0x80,
            (byte)'(',(byte)'B',(byte)'U',(byte)'I',(byte)'L',(byte)')',                (byte)'=',(byte)'B',(byte)'I',(byte)'H',(byte)'4','L'|0x80,
            (byte)'(',(byte)'B',(byte)')',                            (byte)'=','B'|0x80,

            (byte)']','C'|0x80,
            (byte)' ',(byte)'(',(byte)'C',(byte)')',(byte)' ',                    (byte)'=',(byte)'S',(byte)'I',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'C',(byte)'H',(byte)')',(byte)'^',                (byte)'=','K'|0x80,
            (byte)'^',(byte)'E',(byte)'(',(byte)'C',(byte)'H',(byte)')',                (byte)'=','K'|0x80,
            (byte)'(',(byte)'C',(byte)'H',(byte)'A',(byte)')',(byte)'R',(byte)'#',            (byte)'=',(byte)'K',(byte)'E',(byte)'H','5'|0x80,
            (byte)'(',(byte)'C',(byte)'H',(byte)')',                        (byte)'=',(byte)'C','H'|0x80,
            (byte)' ',(byte)'S',(byte)'(',(byte)'C',(byte)'I',(byte)')',(byte)'#',            (byte)'=',(byte)'S',(byte)'A',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'C',(byte)'I',(byte)')',(byte)'A',                    (byte)'=',(byte)'S','H'|0x80,
            (byte)'(',(byte)'C',(byte)'I',(byte)')',(byte)'O',                    (byte)'=',(byte)'S','H'|0x80,
            (byte)'(',(byte)'C',(byte)'I',(byte)')',(byte)'E',(byte)'N',                (byte)'=',(byte)'S','H'|0x80,
            (byte)'(',(byte)'C',(byte)'I',(byte)'T',(byte)'Y',(byte)')',                (byte)'=',(byte)'S',(byte)'I',(byte)'H',(byte)'T',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'C',(byte)')',(byte)'+',                        (byte)'=','S'|0x80,
            (byte)'(',(byte)'C',(byte)'K',(byte)')',                        (byte)'=','K'|0x80,
            (byte)'(',(byte)'C',(byte)'O',(byte)'M',(byte)'M',(byte)'O',(byte)'D',(byte)'O',(byte)'R',(byte)'E',(byte)')',(byte)'=',(byte)'K',(byte)'A',(byte)'A',(byte)'4',(byte)'M',(byte)'A',(byte)'H',(byte)'D',(byte)'O',(byte)'H','R'|0x80,
            (byte)'(',(byte)'C',(byte)'O',(byte)'M',(byte)')',                    (byte)'=',(byte)'K',(byte)'A',(byte)'H','M'|0x80,
            (byte)'(',(byte)'C',(byte)'U',(byte)'I',(byte)'T',(byte)')',                (byte)'=',(byte)'K',(byte)'I',(byte)'H','T'|0x80,
            (byte)'(',(byte)'C',(byte)'R',(byte)'E',(byte)'A',(byte)')',                (byte)'=',(byte)'K',(byte)'R',(byte)'I',(byte)'Y',(byte)'E','Y'|0x80,
            (byte)'(',(byte)'C',(byte)')',                            (byte)'=','K'|0x80,

            (byte)']','D'|0x80,
            (byte)' ',(byte)'(',(byte)'D',(byte)')',(byte)' ',                    (byte)'=',(byte)'D',(byte)'I',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'D',(byte)'R',(byte)'.',(byte)')',(byte)' ',            (byte)'=',(byte)'D',(byte)'A',(byte)'A',(byte)'4',(byte)'K',(byte)'T',(byte)'E','R'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'D',(byte)'E',(byte)'D',(byte)')',(byte)' ',        (byte)'=',(byte)'D',(byte)'I',(byte)'H','D'|0x80,
            (byte)'.',(byte)'E',(byte)'(',(byte)'D',(byte)')',(byte)' ',                (byte)'=','D'|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'E',(byte)'(',(byte)'D',(byte)')',(byte)' ',        (byte)'=','T'|0x80,
            (byte)' ',(byte)'(',(byte)'D',(byte)'E',(byte)')',(byte)'^',(byte)'#',            (byte)'=',(byte)'D',(byte)'I','H'|0x80,
            (byte)' ',(byte)'(',(byte)'D',(byte)'O',(byte)')',(byte)' ',                (byte)'=',(byte)'D',(byte)'U','W'|0x80,
            (byte)' ',(byte)'(',(byte)'D',(byte)'O',(byte)'E',(byte)'S',(byte)')',            (byte)'=',(byte)'D',(byte)'A',(byte)'H','Z'|0x80,
            (byte)'(',(byte)'D',(byte)'O',(byte)'N',(byte)'E',(byte)')',(byte)' ',            (byte)'=',(byte)'D',(byte)'A',(byte)'H',(byte)'5','N'|0x80,
            (byte)'(',(byte)'D',(byte)'O',(byte)'I',(byte)'N',(byte)'G',(byte)')',            (byte)'=',(byte)'D',(byte)'U',(byte)'W',(byte)'4',(byte)'I',(byte)'H',(byte)'N','X'|0x80,
            (byte)' ',(byte)'(',(byte)'D',(byte)'O',(byte)'W',(byte)')',                (byte)'=',(byte)'D',(byte)'A','W'|0x80,
            (byte)'#',(byte)'(',(byte)'D',(byte)'U',(byte)')',(byte)'A',                (byte)'=',(byte)'J',(byte)'U','W'|0x80,
            (byte)'#',(byte)'(',(byte)'D',(byte)'U',(byte)')',(byte)'^',(byte)'#',            (byte)'=',(byte)'J',(byte)'A','X'|0x80,
            (byte)'(',(byte)'D',(byte)')',                            (byte)'=','D'|0x80,

            (byte)']','E'|0x80,
            (byte)' ',(byte)'(',(byte)'E',(byte)')',(byte)' ',                    (byte)'=',(byte)'I',(byte)'Y',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)')',(byte)' ','='|0x80,
            (byte)'\'',(byte)':',(byte)'^',(byte)'(',(byte)'E',(byte)')',(byte)' ','='|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'E',(byte)')',(byte)' ',                (byte)'=',(byte)'I','Y'|0x80,
            (byte)'#',(byte)'(',(byte)'E',(byte)'D',(byte)')',(byte)' ',                (byte)'=','D'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)')',(byte)'D',(byte)' ','='|0x80,
            (byte)'(',(byte)'E',(byte)'V',(byte)')',(byte)'E',(byte)'R',                (byte)'=',(byte)'E',(byte)'H',(byte)'4','V'|0x80,
            (byte)'(',(byte)'E',(byte)')',(byte)'^',(byte)'%',                    (byte)'=',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'E',(byte)'R',(byte)'I',(byte)')',(byte)'#',                (byte)'=',(byte)'I',(byte)'Y',(byte)'4',(byte)'R',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'E',(byte)'R',(byte)'I',(byte)')',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4',(byte)'R',(byte)'I','H'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)'R',(byte)')',(byte)'#',            (byte)'=',(byte)'E','R'|0x80,
            (byte)'(',(byte)'E',(byte)'R',(byte)'R',(byte)'O',(byte)'R',(byte)')',            (byte)'=',(byte)'E',(byte)'H',(byte)'4',(byte)'R',(byte)'O',(byte)'H','R'|0x80,
            (byte)'(',(byte)'E',(byte)'R',(byte)'A',(byte)'S',(byte)'E',(byte)')',            (byte)'=',(byte)'I',(byte)'H',(byte)'R',(byte)'E',(byte)'Y',(byte)'5','S'|0x80,
            (byte)'(',(byte)'E',(byte)'R',(byte)')',(byte)'#',                    (byte)'=',(byte)'E',(byte)'H','R'|0x80,
            (byte)'(',(byte)'E',(byte)'R',(byte)')',                        (byte)'=',(byte)'E','R'|0x80,
            (byte)' ',(byte)'(',(byte)'E',(byte)'V',(byte)'E',(byte)'N',(byte)')',            (byte)'=',(byte)'I',(byte)'Y',(byte)'V',(byte)'E',(byte)'H','N'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)')',(byte)'W','='|0x80,
            (byte)'@',(byte)'(',(byte)'E',(byte)'W',(byte)')',                    (byte)'=',(byte)'U','W'|0x80,
            (byte)'(',(byte)'E',(byte)'W',(byte)')',                        (byte)'=',(byte)'Y',(byte)'U','W'|0x80,
            (byte)'(',(byte)'E',(byte)')',(byte)'O',                        (byte)'=',(byte)'I','Y'|0x80,
            (byte)'#',(byte)':',(byte)'&',(byte)'(',(byte)'E',(byte)'S',(byte)')',(byte)' ',        (byte)'=',(byte)'I',(byte)'H','Z'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)')',(byte)'S',(byte)' ','='|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)'L',(byte)'Y',(byte)')',(byte)' ',        (byte)'=',(byte)'L',(byte)'I','Y'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)'M',(byte)'E',(byte)'N',(byte)'T',(byte)')',    (byte)'=',(byte)'M',(byte)'E',(byte)'H',(byte)'N','T'|0x80,
            (byte)'(',(byte)'E',(byte)'F',(byte)'U',(byte)'L',(byte)')',                (byte)'=',(byte)'F',(byte)'U',(byte)'H','L'|0x80,
            (byte)'(',(byte)'E',(byte)'E',(byte)')',                        (byte)'=',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'E',(byte)'A',(byte)'R',(byte)'N',(byte)')',                (byte)'=',(byte)'E',(byte)'R',(byte)'5','N'|0x80,
            (byte)' ',(byte)'(',(byte)'E',(byte)'A',(byte)'R',(byte)')',(byte)'^',            (byte)'=',(byte)'E',(byte)'R','5'|0x80,
            (byte)'(',(byte)'E',(byte)'A',(byte)'D',(byte)')',                    (byte)'=',(byte)'E',(byte)'H','D'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'E',(byte)'A',(byte)')',(byte)' ',            (byte)'=',(byte)'I',(byte)'Y',(byte)'A','X'|0x80,
            (byte)'(',(byte)'E',(byte)'A',(byte)')',(byte)'S',(byte)'U',                (byte)'=',(byte)'E',(byte)'H','5'|0x80,
            (byte)'(',(byte)'E',(byte)'A',(byte)')',                        (byte)'=',(byte)'I',(byte)'Y','5'|0x80,
            (byte)'(',(byte)'E',(byte)'I',(byte)'G',(byte)'H',(byte)')',                (byte)'=',(byte)'E',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'E',(byte)'I',(byte)')',                        (byte)'=',(byte)'I',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'E',(byte)'Y',(byte)'E',(byte)')',                (byte)'=',(byte)'A',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'E',(byte)'Y',(byte)')',                        (byte)'=',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'E',(byte)'U',(byte)')',                        (byte)'=',(byte)'Y',(byte)'U',(byte)'W','5'|0x80,
            (byte)'(',(byte)'E',(byte)'Q',(byte)'U',(byte)'A',(byte)'L',(byte)')',            (byte)'=',(byte)'I',(byte)'Y',(byte)'4',(byte)'K',(byte)'W',(byte)'U','L'|0x80,
            (byte)'(',(byte)'E',(byte)')',                            (byte)'=',(byte)'E','H'|0x80,

            (byte)']','F'|0x80,
            (byte)' ',(byte)'(',(byte)'F',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','F'|0x80,
            (byte)'(',(byte)'F',(byte)'U',(byte)'L',(byte)')',                    (byte)'=',(byte)'F',(byte)'U',(byte)'H','L'|0x80,
            (byte)'(',(byte)'F',(byte)'R',(byte)'I',(byte)'E',(byte)'N',(byte)'D',(byte)')',        (byte)'=',(byte)'F',(byte)'R',(byte)'E',(byte)'H',(byte)'5',(byte)'N','D'|0x80,
            (byte)'(',(byte)'F',(byte)'A',(byte)'T',(byte)'H',(byte)'E',(byte)'R',(byte)')',        (byte)'=',(byte)'F',(byte)'A',(byte)'A',(byte)'4',(byte)'D',(byte)'H',(byte)'E','R'|0x80,
            (byte)'(',(byte)'F',(byte)')',(byte)'F','='|0x80,
            (byte)'(',(byte)'F',(byte)')',                            (byte)'=','F'|0x80,

            (byte)']','G'|0x80,
            (byte)' ',(byte)'(',(byte)'G',(byte)')',(byte)' ',                    (byte)'=',(byte)'J',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'G',(byte)'I',(byte)'V',(byte)')',                    (byte)'=',(byte)'G',(byte)'I',(byte)'H',(byte)'5','V'|0x80,
            (byte)' ',(byte)'(',(byte)'G',(byte)')',(byte)'I',(byte)'^',                (byte)'=','G'|0x80,
            (byte)'(',(byte)'G',(byte)'E',(byte)')',(byte)'T',                    (byte)'=',(byte)'G',(byte)'E',(byte)'H','5'|0x80,
            (byte)'S',(byte)'U',(byte)'(',(byte)'G',(byte)'G',(byte)'E',(byte)'S',(byte)')',        (byte)'=',(byte)'G',(byte)'J',(byte)'E',(byte)'H',(byte)'4','S'|0x80,
            (byte)'(',(byte)'G',(byte)'G',(byte)')',                        (byte)'=','G'|0x80,
            (byte)' ',(byte)'B',(byte)'#',(byte)'(',(byte)'G',(byte)')',                (byte)'=','G'|0x80,
            (byte)'(',(byte)'G',(byte)')',(byte)'+',                        (byte)'=','J'|0x80,
            (byte)'(',(byte)'G',(byte)'R',(byte)'E',(byte)'A',(byte)'T',(byte)')',            (byte)'=',(byte)'G',(byte)'R',(byte)'E',(byte)'Y',(byte)'4','T'|0x80,
            (byte)'(',(byte)'G',(byte)'O',(byte)'N',(byte)')',(byte)'E',                (byte)'=',(byte)'G',(byte)'A',(byte)'O',(byte)'5','N'|0x80,
            (byte)'#',(byte)'(',(byte)'G',(byte)'H',(byte)')','='|0x80,
            (byte)' ',(byte)'(',(byte)'G',(byte)'N',(byte)')',                    (byte)'=','N'|0x80,
            (byte)'(',(byte)'G',(byte)')',                            (byte)'=','G'|0x80,

            (byte)']','H'|0x80,
            (byte)' ',(byte)'(',(byte)'H',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'Y',(byte)'4',(byte)'C','H'|0x80,
            (byte)' ',(byte)'(',(byte)'H',(byte)'A',(byte)'V',(byte)')',                (byte)'=',(byte)'/',(byte)'H',(byte)'A',(byte)'E',(byte)'6','V'|0x80,
            (byte)' ',(byte)'(',(byte)'H',(byte)'E',(byte)'R',(byte)'E',(byte)')',            (byte)'=',(byte)'/',(byte)'H',(byte)'I',(byte)'Y','R'|0x80,
            (byte)' ',(byte)'(',(byte)'H',(byte)'O',(byte)'U',(byte)'R',(byte)')',            (byte)'=',(byte)'A',(byte)'W',(byte)'5',(byte)'E','R'|0x80,
            (byte)'(',(byte)'H',(byte)'O',(byte)'W',(byte)')',                    (byte)'=',(byte)'/',(byte)'H',(byte)'A','W'|0x80,
            (byte)'(',(byte)'H',(byte)')',(byte)'#',                        (byte)'=',(byte)'/','H'|0x80,
            (byte)'(',(byte)'H',(byte)')','='|0x80,

            (byte)']','I'|0x80,
            (byte)' ',(byte)'(',(byte)'I',(byte)'N',(byte)')',                    (byte)'=',(byte)'I',(byte)'H','N'|0x80,
            (byte)' ',(byte)'(',(byte)'I',(byte)')',(byte)' ',                    (byte)'=',(byte)'A',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'I',(byte)')',(byte)' ',                        (byte)'=',(byte)'A','Y'|0x80,
            (byte)'(',(byte)'I',(byte)'N',(byte)')',(byte)'D',                    (byte)'=',(byte)'A',(byte)'Y',(byte)'5','N'|0x80,
            (byte)'S',(byte)'E',(byte)'M',(byte)'(',(byte)'I',(byte)')',                (byte)'=',(byte)'I','Y'|0x80,
            (byte)' ',(byte)'A',(byte)'N',(byte)'T',(byte)'(',(byte)'I',(byte)')',            (byte)'=',(byte)'A','Y'|0x80,
            (byte)'(',(byte)'I',(byte)'E',(byte)'R',(byte)')',                    (byte)'=',(byte)'I',(byte)'Y',(byte)'E','R'|0x80,
            (byte)'#',(byte)':',(byte)'R',(byte)'(',(byte)'I',(byte)'E',(byte)'D',(byte)')',(byte)' ',    (byte)'=',(byte)'I',(byte)'Y','D'|0x80,
            (byte)'(',(byte)'I',(byte)'E',(byte)'D',(byte)')',(byte)' ',                (byte)'=',(byte)'A',(byte)'Y',(byte)'5','D'|0x80,
            (byte)'(',(byte)'I',(byte)'E',(byte)'N',(byte)')',                    (byte)'=',(byte)'I',(byte)'Y',(byte)'E',(byte)'H','N'|0x80,
            (byte)'(',(byte)'I',(byte)'E',(byte)')',(byte)'T',                    (byte)'=',(byte)'A',(byte)'Y',(byte)'4',(byte)'E','H'|0x80,
            (byte)'(',(byte)'I',(byte)'\'',(byte)')',                        (byte)'=',(byte)'A',(byte)'Y','5'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'I',(byte)')',(byte)'^',(byte)'%',            (byte)'=',(byte)'A',(byte)'Y','5'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'I',(byte)'E',(byte)')',(byte)' ',            (byte)'=',(byte)'A',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'I',(byte)')',(byte)'%',                        (byte)'=',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'I',(byte)'E',(byte)')',                        (byte)'=',(byte)'I',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'I',(byte)'D',(byte)'E',(byte)'A',(byte)')',            (byte)'=',(byte)'A',(byte)'Y',(byte)'D',(byte)'I',(byte)'Y',(byte)'5',(byte)'A','H'|0x80,
            (byte)'(',(byte)'I',(byte)')',(byte)'^',(byte)'+',(byte)':',(byte)'#',            (byte)'=',(byte)'I','H'|0x80,
            (byte)'(',(byte)'I',(byte)'R',(byte)')',(byte)'#',                    (byte)'=',(byte)'A',(byte)'Y','R'|0x80,
            (byte)'(',(byte)'I',(byte)'Z',(byte)')',(byte)'%',                    (byte)'=',(byte)'A',(byte)'Y','Z'|0x80,
            (byte)'(',(byte)'I',(byte)'S',(byte)')',(byte)'%',                    (byte)'=',(byte)'A',(byte)'Y','Z'|0x80,
            (byte)'I',(byte)'^',(byte)'(',(byte)'I',(byte)')',(byte)'^',(byte)'#',            (byte)'=',(byte)'I','H'|0x80,
            (byte)'+',(byte)'^',(byte)'(',(byte)'I',(byte)')',(byte)'^',(byte)'+',            (byte)'=',(byte)'A','Y'|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'(',(byte)'I',(byte)')',(byte)'^',(byte)'+',        (byte)'=',(byte)'I','H'|0x80,
            (byte)'(',(byte)'I',(byte)')',(byte)'^',(byte)'+',                    (byte)'=',(byte)'A','Y'|0x80,
            (byte)'(',(byte)'I',(byte)'R',(byte)')',                        (byte)'=',(byte)'E','R'|0x80,
            (byte)'(',(byte)'I',(byte)'G',(byte)'H',(byte)')',                    (byte)'=',(byte)'A',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'I',(byte)'L',(byte)'D',(byte)')',                    (byte)'=',(byte)'A',(byte)'Y',(byte)'5',(byte)'L','D'|0x80,
            (byte)' ',(byte)'(',(byte)'I',(byte)'G',(byte)'N',(byte)')',                (byte)'=',(byte)'I',(byte)'H',(byte)'G','N'|0x80,
            (byte)'(',(byte)'I',(byte)'G',(byte)'N',(byte)')',(byte)' ',                (byte)'=',(byte)'A',(byte)'Y',(byte)'4','N'|0x80,
            (byte)'(',(byte)'I',(byte)'G',(byte)'N',(byte)')',(byte)'^',                (byte)'=',(byte)'A',(byte)'Y',(byte)'4','N'|0x80,
            (byte)'(',(byte)'I',(byte)'G',(byte)'N',(byte)')',(byte)'%',                (byte)'=',(byte)'A',(byte)'Y',(byte)'4','N'|0x80,
            (byte)'(',(byte)'I',(byte)'C',(byte)'R',(byte)'O',(byte)')',                (byte)'=',(byte)'A',(byte)'Y',(byte)'4',(byte)'K',(byte)'R',(byte)'O','H'|0x80,
            (byte)'(',(byte)'I',(byte)'Q',(byte)'U',(byte)'E',(byte)')',                (byte)'=',(byte)'I',(byte)'Y',(byte)'4','K'|0x80,
            (byte)'(',(byte)'I',(byte)')',                            (byte)'=',(byte)'I','H'|0x80,

            (byte)']','J'|0x80,
            (byte)' ',(byte)'(',(byte)'J',(byte)')',(byte)' ',                    (byte)'=',(byte)'J',(byte)'E',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'J',(byte)')',                            (byte)'=','J'|0x80,

            (byte)']','K'|0x80,
            (byte)' ',(byte)'(',(byte)'K',(byte)')',(byte)' ',                    (byte)'=',(byte)'K',(byte)'E',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'K',(byte)')',(byte)'N','='|0x80,
            (byte)'(',(byte)'K',(byte)')',                            (byte)'=','K'|0x80,

            (byte)']','L'|0x80,
            (byte)' ',(byte)'(',(byte)'L',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','L'|0x80,
            (byte)'(',(byte)'L',(byte)'O',(byte)')',(byte)'C',(byte)'#',                (byte)'=',(byte)'L',(byte)'O','W'|0x80,
            (byte)'L',(byte)'(',(byte)'L',(byte)')','='|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'(',(byte)'L',(byte)')',(byte)'%',            (byte)'=',(byte)'U','L'|0x80,
            (byte)'(',(byte)'L',(byte)'E',(byte)'A',(byte)'D',(byte)')',                (byte)'=',(byte)'L',(byte)'I',(byte)'Y','D'|0x80,
            (byte)' ',(byte)'(',(byte)'L',(byte)'A',(byte)'U',(byte)'G',(byte)'H',(byte)')',        (byte)'=',(byte)'L',(byte)'A',(byte)'E',(byte)'4','F'|0x80,
            (byte)'(',(byte)'L',(byte)')',                            (byte)'=','L'|0x80,

            (byte)']','M'|0x80,
            (byte)' ',(byte)'(',(byte)'M',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','M'|0x80,
            (byte)' ',(byte)'(',(byte)'M',(byte)'R',(byte)'.',(byte)')',(byte)' ',            (byte)'=',(byte)'M',(byte)'I',(byte)'H',(byte)'4',(byte)'S',(byte)'T',(byte)'E','R'|0x80,
            (byte)' ',(byte)'(',(byte)'M',(byte)'S',(byte)'.',(byte)')',                (byte)'=',(byte)'M',(byte)'I',(byte)'H',(byte)'5','Z'|0x80,
            (byte)' ',(byte)'(',(byte)'M',(byte)'R',(byte)'S',(byte)'.',(byte)')',(byte)' ',        (byte)'=',(byte)'M',(byte)'I',(byte)'H',(byte)'4',(byte)'S',(byte)'I',(byte)'X','Z'|0x80,
            (byte)'(',(byte)'M',(byte)'O',(byte)'V',(byte)')',                    (byte)'=',(byte)'M',(byte)'U',(byte)'W',(byte)'4','V'|0x80,
            (byte)'(',(byte)'M',(byte)'A',(byte)'C',(byte)'H',(byte)'I',(byte)'N',(byte)')',        (byte)'=',(byte)'M',(byte)'A',(byte)'H',(byte)'S',(byte)'H',(byte)'I',(byte)'Y',(byte)'5','N'|0x80,
            (byte)'M',(byte)'(',(byte)'M',(byte)')','='|0x80,
            (byte)'(',(byte)'M',(byte)')',                            (byte)'=','M'|0x80,

            (byte)']','N'|0x80,
            (byte)' ',(byte)'(',(byte)'N',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','N'|0x80,
            (byte)'E',(byte)'(',(byte)'N',(byte)'G',(byte)')',(byte)'+',                (byte)'=',(byte)'N','J'|0x80,
            (byte)'(',(byte)'N',(byte)'G',(byte)')',(byte)'R',                    (byte)'=',(byte)'N',(byte)'X','G'|0x80,
            (byte)'(',(byte)'N',(byte)'G',(byte)')',(byte)'#',                    (byte)'=',(byte)'N',(byte)'X','G'|0x80,
            (byte)'(',(byte)'N',(byte)'G',(byte)'L',(byte)')',(byte)'%',                (byte)'=',(byte)'N',(byte)'X',(byte)'G',(byte)'U','L'|0x80,
            (byte)'(',(byte)'N',(byte)'G',(byte)')',                        (byte)'=',(byte)'N','X'|0x80,
            (byte)'(',(byte)'N',(byte)'K',(byte)')',                        (byte)'=',(byte)'N',(byte)'X','K'|0x80,
            (byte)' ',(byte)'(',(byte)'N',(byte)'O',(byte)'W',(byte)')',(byte)' ',            (byte)'=',(byte)'N',(byte)'A',(byte)'W','4'|0x80,
            (byte)'N',(byte)'(',(byte)'N',(byte)')','='|0x80,
            (byte)'(',(byte)'N',(byte)'O',(byte)'N',(byte)')',(byte)'E',                (byte)'=',(byte)'N',(byte)'A',(byte)'H',(byte)'4','N'|0x80,
            (byte)'(',(byte)'N',(byte)')',                            (byte)'=','N'|0x80,

            (byte)']','O'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)')',(byte)' ',                    (byte)'=',(byte)'O',(byte)'H',(byte)'4','W'|0x80,
            (byte)'(',(byte)'O',(byte)'F',(byte)')',(byte)' ',                    (byte)'=',(byte)'A',(byte)'H','V'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)'H',(byte)')',(byte)' ',                (byte)'=',(byte)'O',(byte)'W','5'|0x80,
            (byte)'(',(byte)'O',(byte)'R',(byte)'O',(byte)'U',(byte)'G',(byte)'H',(byte)')',        (byte)'=',(byte)'E',(byte)'R',(byte)'4',(byte)'O','W'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'O',(byte)'R',(byte)')',(byte)' ',            (byte)'=',(byte)'E','R'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'O',(byte)'R',(byte)'S',(byte)')',(byte)' ',        (byte)'=',(byte)'E',(byte)'R','Z'|0x80,
            (byte)'(',(byte)'O',(byte)'R',(byte)')',                        (byte)'=',(byte)'A',(byte)'O','R'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)'N',(byte)'E',(byte)')',                (byte)'=',(byte)'W',(byte)'A',(byte)'H','N'|0x80,
            (byte)'#',(byte)'(',(byte)'O',(byte)'N',(byte)'E',(byte)')',(byte)' ',            (byte)'=',(byte)'W',(byte)'A',(byte)'H','N'|0x80,
            (byte)'(',(byte)'O',(byte)'W',(byte)')',                        (byte)'=',(byte)'O','W'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)'V',(byte)'E',(byte)'R',(byte)')',            (byte)'=',(byte)'O',(byte)'W',(byte)'5',(byte)'V',(byte)'E','R'|0x80,
            (byte)'P',(byte)'R',(byte)'(',(byte)'O',(byte)')',(byte)'V',                (byte)'=',(byte)'U',(byte)'W','4'|0x80,
            (byte)'(',(byte)'O',(byte)'V',(byte)')',                        (byte)'=',(byte)'A',(byte)'H',(byte)'4','V'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)'^',(byte)'%',                    (byte)'=',(byte)'O',(byte)'W','5'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)'^',(byte)'E',(byte)'N',                (byte)'=',(byte)'O','W'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)'^',(byte)'I',(byte)'#',                (byte)'=',(byte)'O',(byte)'W','5'|0x80,
            (byte)'(',(byte)'O',(byte)'L',(byte)')',(byte)'D',                    (byte)'=',(byte)'O',(byte)'W',(byte)'4','L'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)'G',(byte)'H',(byte)'T',(byte)')',            (byte)'=',(byte)'A',(byte)'O',(byte)'5','T'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)'G',(byte)'H',(byte)')',                (byte)'=',(byte)'A',(byte)'H',(byte)'5','F'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)'U',(byte)')',                    (byte)'=',(byte)'A','W'|0x80,
            (byte)'H',(byte)'(',(byte)'O',(byte)'U',(byte)')',(byte)'S',(byte)'#',            (byte)'=',(byte)'A',(byte)'W','4'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)'S',(byte)')',                    (byte)'=',(byte)'A',(byte)'X','S'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)'R',(byte)')',                    (byte)'=',(byte)'O',(byte)'H','R'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)'L',(byte)'D',(byte)')',                (byte)'=',(byte)'U',(byte)'H',(byte)'5','D'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)')',(byte)'^',(byte)'L',                (byte)'=',(byte)'A',(byte)'H','5'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)'P',(byte)')',                    (byte)'=',(byte)'U',(byte)'W',(byte)'5','P'|0x80,
            (byte)'(',(byte)'O',(byte)'U',(byte)')',                        (byte)'=',(byte)'A','W'|0x80,
            (byte)'(',(byte)'O',(byte)'Y',(byte)')',                        (byte)'=',(byte)'O','Y'|0x80,
            (byte)'(',(byte)'O',(byte)'I',(byte)'N',(byte)'G',(byte)')',                (byte)'=',(byte)'O',(byte)'W',(byte)'4',(byte)'I',(byte)'H',(byte)'N','X'|0x80,
            (byte)'(',(byte)'O',(byte)'I',(byte)')',                        (byte)'=',(byte)'O',(byte)'Y','5'|0x80,
            (byte)'(',(byte)'O',(byte)'O',(byte)'R',(byte)')',                    (byte)'=',(byte)'O',(byte)'H',(byte)'5','R'|0x80,
            (byte)'(',(byte)'O',(byte)'O',(byte)'K',(byte)')',                    (byte)'=',(byte)'U',(byte)'H',(byte)'5','K'|0x80,
            (byte)'F',(byte)'(',(byte)'O',(byte)'O',(byte)'D',(byte)')',                (byte)'=',(byte)'U',(byte)'W',(byte)'5','D'|0x80,
            (byte)'L',(byte)'(',(byte)'O',(byte)'O',(byte)'D',(byte)')',                (byte)'=',(byte)'A',(byte)'H',(byte)'5','D'|0x80,
            (byte)'M',(byte)'(',(byte)'O',(byte)'O',(byte)'D',(byte)')',                (byte)'=',(byte)'U',(byte)'W',(byte)'5','D'|0x80,
            (byte)'(',(byte)'O',(byte)'O',(byte)'D',(byte)')',                    (byte)'=',(byte)'U',(byte)'H',(byte)'5','D'|0x80,
            (byte)'F',(byte)'(',(byte)'O',(byte)'O',(byte)'T',(byte)')',                (byte)'=',(byte)'U',(byte)'H',(byte)'5','T'|0x80,
            (byte)'(',(byte)'O',(byte)'O',(byte)')',                        (byte)'=',(byte)'U',(byte)'W','5'|0x80,
            (byte)'(',(byte)'O',(byte)'\'',(byte)')',                        (byte)'=',(byte)'O','H'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)'E',                        (byte)'=',(byte)'O','W'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)' ',                        (byte)'=',(byte)'O','W'|0x80,
            (byte)'(',(byte)'O',(byte)'A',(byte)')',                        (byte)'=',(byte)'O',(byte)'W','4'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)'N',(byte)'L',(byte)'Y',(byte)')',            (byte)'=',(byte)'O',(byte)'W',(byte)'4',(byte)'N',(byte)'L',(byte)'I','Y'|0x80,
            (byte)' ',(byte)'(',(byte)'O',(byte)'N',(byte)'C',(byte)'E',(byte)')',            (byte)'=',(byte)'W',(byte)'A',(byte)'H',(byte)'4',(byte)'N','S'|0x80,
            (byte)'(',(byte)'O',(byte)'N',(byte)'\'',(byte)'T',(byte)')',                (byte)'=',(byte)'O',(byte)'W',(byte)'4',(byte)'N','T'|0x80,
            (byte)'C',(byte)'(',(byte)'O',(byte)')',(byte)'N',                    (byte)'=',(byte)'A','A'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)'N',(byte)'G',                    (byte)'=',(byte)'A','O'|0x80,
            (byte)' ',(byte)':',(byte)'^',(byte)'(',(byte)'O',(byte)')',(byte)'N',            (byte)'=',(byte)'A','H'|0x80,
            (byte)'I',(byte)'(',(byte)'O',(byte)'N',(byte)')',                    (byte)'=',(byte)'U','N'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'O',(byte)'N',(byte)')',                (byte)'=',(byte)'U','N'|0x80,
            (byte)'#',(byte)'^',(byte)'(',(byte)'O',(byte)'N',(byte)')',                (byte)'=',(byte)'U','N'|0x80,
            (byte)'(',(byte)'O',(byte)')',(byte)'S',(byte)'T',                    (byte)'=',(byte)'O','W'|0x80,
            (byte)'(',(byte)'O',(byte)'F',(byte)')',(byte)'^',                    (byte)'=',(byte)'A',(byte)'O',(byte)'4','F'|0x80,
            (byte)'(',(byte)'O',(byte)'T',(byte)'H',(byte)'E',(byte)'R',(byte)')',            (byte)'=',(byte)'A',(byte)'H',(byte)'5',(byte)'D',(byte)'H',(byte)'E','R'|0x80,
            (byte)'R',(byte)'(',(byte)'O',(byte)')',(byte)'B',                    (byte)'=',(byte)'R',(byte)'A','A'|0x80,
            (byte)'^',(byte)'R',(byte)'(',(byte)'O',(byte)')',(byte)':',(byte)'#',            (byte)'=',(byte)'O',(byte)'W','5'|0x80,
            (byte)'(',(byte)'O',(byte)'S',(byte)'S',(byte)')',(byte)' ',                (byte)'=',(byte)'A',(byte)'O',(byte)'5','S'|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'(',(byte)'O',(byte)'M',(byte)')',            (byte)'=',(byte)'A',(byte)'H','M'|0x80,
            (byte)'(',(byte)'O',(byte)')',                            (byte)'=',(byte)'A','A'|0x80,

            (byte)']','P'|0x80,
            (byte)' ',(byte)'(',(byte)'P',(byte)')',(byte)' ',                    (byte)'=',(byte)'P',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'P',(byte)'H',(byte)')',                        (byte)'=','F'|0x80,
            (byte)'(',(byte)'P',(byte)'E',(byte)'O',(byte)'P',(byte)'L',(byte)')',            (byte)'=',(byte)'P',(byte)'I',(byte)'Y',(byte)'5',(byte)'P',(byte)'U','L'|0x80,
            (byte)'(',(byte)'P',(byte)'O',(byte)'W',(byte)')',                    (byte)'=',(byte)'P',(byte)'A',(byte)'W','4'|0x80,
            (byte)'(',(byte)'P',(byte)'U',(byte)'T',(byte)')',(byte)' ',                (byte)'=',(byte)'P',(byte)'U',(byte)'H','T'|0x80,
            (byte)'(',(byte)'P',(byte)')',(byte)'P','='|0x80,
            (byte)'(',(byte)'P',(byte)')',(byte)'S','='|0x80,
            (byte)'(',(byte)'P',(byte)')',(byte)'N','='|0x80,
            (byte)'(',(byte)'P',(byte)'R',(byte)'O',(byte)'F',(byte)'.',(byte)')',            (byte)'=',(byte)'P',(byte)'R',(byte)'O',(byte)'H',(byte)'F',(byte)'E',(byte)'H',(byte)'4',(byte)'S',(byte)'E','R'|0x80,
            (byte)'(',(byte)'P',(byte)')',                            (byte)'=','P'|0x80,

            (byte)']','Q'|0x80,
            (byte)' ',(byte)'(',(byte)'Q',(byte)')',(byte)' ',                    (byte)'=',(byte)'K',(byte)'Y',(byte)'U',(byte)'W','4'|0x80,
            (byte)'(',(byte)'Q',(byte)'U',(byte)'A',(byte)'R',(byte)')',                (byte)'=',(byte)'K',(byte)'W',(byte)'O',(byte)'H',(byte)'5','R'|0x80,
            (byte)'(',(byte)'Q',(byte)'U',(byte)')',                        (byte)'=',(byte)'K','W'|0x80,
            (byte)'(',(byte)'Q',(byte)')',                            (byte)'=','K'|0x80,
            (byte)']','R'|0x80,
            (byte)' ',(byte)'(',(byte)'R',(byte)')',(byte)' ',                    (byte)'=',(byte)'A',(byte)'A',(byte)'5','R'|0x80,
            (byte)' ',(byte)'(',(byte)'R',(byte)'E',(byte)')',(byte)'^',(byte)'#',            (byte)'=',(byte)'R',(byte)'I','Y'|0x80,
            (byte)'(',(byte)'R',(byte)')',(byte)'R','='|0x80,
            (byte)'(',(byte)'R',(byte)')',                            (byte)'=','R'|0x80,

            (byte)']','S'|0x80,
            (byte)' ',(byte)'(',(byte)'S',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4','S'|0x80,
            (byte)'(',(byte)'S',(byte)'H',(byte)')',                        (byte)'=',(byte)'S','H'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'I',(byte)'O',(byte)'N',(byte)')',            (byte)'=',(byte)'Z',(byte)'H',(byte)'U','N'|0x80,
            (byte)'(',(byte)'S',(byte)'O',(byte)'M',(byte)'E',(byte)')',                (byte)'=',(byte)'S',(byte)'A',(byte)'H','M'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'U',(byte)'R',(byte)')',(byte)'#',            (byte)'=',(byte)'Z',(byte)'H',(byte)'E','R'|0x80,
            (byte)'(',(byte)'S',(byte)'U',(byte)'R',(byte)')',(byte)'#',                (byte)'=',(byte)'S',(byte)'H',(byte)'E','R'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'U',(byte)')',(byte)'#',                (byte)'=',(byte)'Z',(byte)'H',(byte)'U','W'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'S',(byte)'U',(byte)')',(byte)'#',            (byte)'=',(byte)'S',(byte)'H',(byte)'U','W'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'E',(byte)'D',(byte)')',                (byte)'=',(byte)'Z','D'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)')',(byte)'#',                    (byte)'=','Z'|0x80,
            (byte)'(',(byte)'S',(byte)'A',(byte)'I',(byte)'D',(byte)')',                (byte)'=',(byte)'S',(byte)'E',(byte)'H','D'|0x80,
            (byte)'^',(byte)'(',(byte)'S',(byte)'I',(byte)'O',(byte)'N',(byte)')',            (byte)'=',(byte)'S',(byte)'H',(byte)'U','N'|0x80,
            (byte)'(',(byte)'S',(byte)')',(byte)'S','='|0x80,
            (byte)'.',(byte)'(',(byte)'S',(byte)')',(byte)' ',                    (byte)'=','Z'|0x80,
            (byte)'#',(byte)':',(byte)'.',(byte)'E',(byte)'(',(byte)'S',(byte)')',(byte)' ',        (byte)'=','Z'|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'#',(byte)'(',(byte)'S',(byte)')',(byte)' ',        (byte)'=','S'|0x80,
            (byte)'U',(byte)'(',(byte)'S',(byte)')',(byte)' ',                    (byte)'=','S'|0x80,
            (byte)' ',(byte)':',(byte)'#',(byte)'(',(byte)'S',(byte)')',(byte)' ',            (byte)'=','Z'|0x80,
            (byte)'#',(byte)'#',(byte)'(',(byte)'S',(byte)')',(byte)' ',                (byte)'=','Z'|0x80,
            (byte)' ',(byte)'(',(byte)'S',(byte)'C',(byte)'H',(byte)')',                (byte)'=',(byte)'S','K'|0x80,
            (byte)'(',(byte)'S',(byte)')',(byte)'C',(byte)'+','='|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'M',(byte)')',                    (byte)'=',(byte)'Z',(byte)'U','M'|0x80,
            (byte)'#',(byte)'(',(byte)'S',(byte)'N',(byte)')',(byte)'\'',                (byte)'=',(byte)'Z',(byte)'U','M'|0x80,
            (byte)'(',(byte)'S',(byte)'T',(byte)'L',(byte)'E',(byte)')',                (byte)'=',(byte)'S',(byte)'U','L'|0x80,
            (byte)'(',(byte)'S',(byte)')',                            (byte)'=','S'|0x80,

            (byte)']','T'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)')',(byte)' ',                    (byte)'=',(byte)'T',(byte)'I',(byte)'Y','4'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)')',(byte)' ',(byte)'#',        (byte)'=',(byte)'D',(byte)'H',(byte)'I','Y'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)')',(byte)' ',            (byte)'=',(byte)'D',(byte)'H',(byte)'A','X'|0x80,
            (byte)'(',(byte)'T',(byte)'O',(byte)')',(byte)' ',                    (byte)'=',(byte)'T',(byte)'U','X'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'A',(byte)'T',(byte)')',            (byte)'=',(byte)'D',(byte)'H',(byte)'A',(byte)'E','T'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'I',(byte)'S',(byte)')',(byte)' ',        (byte)'=',(byte)'D',(byte)'H',(byte)'I',(byte)'H','S'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'Y',(byte)')',            (byte)'=',(byte)'D',(byte)'H',(byte)'E','Y'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'R',(byte)'E',(byte)')',        (byte)'=',(byte)'D',(byte)'H',(byte)'E',(byte)'H','R'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'R',(byte)')',                (byte)'=',(byte)'D',(byte)'H',(byte)'E','R'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'I',(byte)'R',(byte)')',            (byte)'=',(byte)'D',(byte)'H',(byte)'E',(byte)'H','R'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'A',(byte)'N',(byte)')',(byte)' ',        (byte)'=',(byte)'D',(byte)'H',(byte)'A',(byte)'E','N'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'M',(byte)')',(byte)' ',        (byte)'=',(byte)'D',(byte)'H',(byte)'A',(byte)'E','N'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'S',(byte)'E',(byte)')',(byte)' ',        (byte)'=',(byte)'D',(byte)'H',(byte)'I',(byte)'Y','Z'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'E',(byte)'N',(byte)')',            (byte)'=',(byte)'D',(byte)'H',(byte)'E',(byte)'H','N'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)'R',(byte)'O',(byte)'U',(byte)'G',(byte)'H',(byte)')',    (byte)'=',(byte)'T',(byte)'H',(byte)'R',(byte)'U',(byte)'W','4'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)'O',(byte)'S',(byte)'E',(byte)')',            (byte)'=',(byte)'D',(byte)'H',(byte)'O',(byte)'H','Z'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)'O',(byte)'U',(byte)'G',(byte)'H',(byte)')',(byte)' ',    (byte)'=',(byte)'D',(byte)'H',(byte)'O','W'|0x80,
            (byte)'(',(byte)'T',(byte)'O',(byte)'D',(byte)'A',(byte)'Y',(byte)')',            (byte)'=',(byte)'T',(byte)'U',(byte)'X',(byte)'D',(byte)'E','Y'|0x80,
            (byte)'(',(byte)'T',(byte)'O',(byte)'M',(byte)'O',(byte)')',(byte)'R',(byte)'R',(byte)'O',(byte)'W',(byte)'=',(byte)'T',(byte)'U',(byte)'M',(byte)'A',(byte)'A','5'|0x80,
            (byte)'(',(byte)'T',(byte)'O',(byte)')',(byte)'T',(byte)'A',(byte)'L',            (byte)'=',(byte)'T',(byte)'O',(byte)'W','5'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'H',(byte)'U',(byte)'S',(byte)')',            (byte)'=',(byte)'D',(byte)'H',(byte)'A',(byte)'H',(byte)'4','S'|0x80,
            (byte)'(',(byte)'T',(byte)'H',(byte)')',                        (byte)'=',(byte)'T','H'|0x80,
            (byte)'#',(byte)':',(byte)'(',(byte)'T',(byte)'E',(byte)'D',(byte)')',            (byte)'=',(byte)'T',(byte)'I',(byte)'X','D'|0x80,
            (byte)'S',(byte)'(',(byte)'T',(byte)'I',(byte)')',(byte)'#',(byte)'N',            (byte)'=',(byte)'C','H'|0x80,
            (byte)'(',(byte)'T',(byte)'I',(byte)')',(byte)'O',                    (byte)'=',(byte)'S','H'|0x80,
            (byte)'(',(byte)'T',(byte)'I',(byte)')',(byte)'A',                    (byte)'=',(byte)'S','H'|0x80,
            (byte)'(',(byte)'T',(byte)'I',(byte)'E',(byte)'N',(byte)')',                (byte)'=',(byte)'S',(byte)'H',(byte)'U','N'|0x80,
            (byte)'(',(byte)'T',(byte)'U',(byte)'R',(byte)')',(byte)'#',                (byte)'=',(byte)'C',(byte)'H',(byte)'E','R'|0x80,
            (byte)'(',(byte)'T',(byte)'U',(byte)')',(byte)'A',                    (byte)'=',(byte)'C',(byte)'H',(byte)'U','W'|0x80,
            (byte)' ',(byte)'(',(byte)'T',(byte)'W',(byte)'O',(byte)')',                (byte)'=',(byte)'T',(byte)'U','W'|0x80,
            (byte)'&',(byte)'(',(byte)'T',(byte)')',(byte)'E',(byte)'N',(byte)' ','='|0x80,
            (byte)'(',(byte)'T',(byte)')',                            (byte)'=','T'|0x80,

            (byte)']','U'|0x80,
            (byte)' ',(byte)'(',(byte)'U',(byte)')',(byte)' ',                    (byte)'=',(byte)'Y',(byte)'U',(byte)'W','4'|0x80,
            (byte)' ',(byte)'(',(byte)'U',(byte)'N',(byte)')',(byte)'I',                (byte)'=',(byte)'Y',(byte)'U',(byte)'W','N'|0x80,
            (byte)' ',(byte)'(',(byte)'U',(byte)'N',(byte)')',                    (byte)'=',(byte)'A',(byte)'H','N'|0x80,
            (byte)' ',(byte)'(',(byte)'U',(byte)'P',(byte)'O',(byte)'N',(byte)')',            (byte)'=',(byte)'A',(byte)'X',(byte)'P',(byte)'A',(byte)'O','N'|0x80,
            (byte)'@',(byte)'(',(byte)'U',(byte)'R',(byte)')',(byte)'#',                (byte)'=',(byte)'U',(byte)'H',(byte)'4','R'|0x80,
            (byte)'(',(byte)'U',(byte)'R',(byte)')',(byte)'#',                    (byte)'=',(byte)'Y',(byte)'U',(byte)'H',(byte)'4','R'|0x80,
            (byte)'(',(byte)'U',(byte)'R',(byte)')',                        (byte)'=',(byte)'E','R'|0x80,
            (byte)'(',(byte)'U',(byte)')',(byte)'^',(byte)' ',                    (byte)'=',(byte)'A','H'|0x80,
            (byte)'(',(byte)'U',(byte)')',(byte)'^',(byte)'^',                    (byte)'=',(byte)'A',(byte)'H','5'|0x80,
            (byte)'(',(byte)'U',(byte)'Y',(byte)')',                        (byte)'=',(byte)'A',(byte)'Y','5'|0x80,
            (byte)' ',(byte)'G',(byte)'(',(byte)'U',(byte)')',(byte)'#','='|0x80,
            (byte)'G',(byte)'(',(byte)'U',(byte)')',(byte)'%','='|0x80,
            (byte)'G',(byte)'(',(byte)'U',(byte)')',(byte)'#',                    (byte)'=','W'|0x80,
            (byte)'#',(byte)'N',(byte)'(',(byte)'U',(byte)')',                    (byte)'=',(byte)'Y',(byte)'U','W'|0x80,
            (byte)'@',(byte)'(',(byte)'U',(byte)')',                        (byte)'=',(byte)'U','W'|0x80,
            (byte)'(',(byte)'U',(byte)')',                            (byte)'=',(byte)'Y',(byte)'U','W'|0x80,

            (byte)']','V'|0x80,
            (byte)' ',(byte)'(',(byte)'V',(byte)')',(byte)' ',                    (byte)'=',(byte)'V',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'V',(byte)'I',(byte)'E',(byte)'W',(byte)')',                (byte)'=',(byte)'V',(byte)'Y',(byte)'U',(byte)'W','5'|0x80,
            (byte)'(',(byte)'V',(byte)')',                            (byte)'=','V'|0x80,

            (byte)']','W'|0x80,
            (byte)' ',(byte)'(',(byte)'W',(byte)')',(byte)' ',                    (byte)'=',(byte)'D',(byte)'A',(byte)'H',(byte)'4',(byte)'B',(byte)'U',(byte)'L',(byte)'Y',(byte)'U','W'|0x80,
            (byte)' ',(byte)'(',(byte)'W',(byte)'E',(byte)'R',(byte)'E',(byte)')',            (byte)'=',(byte)'W',(byte)'E','R'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)')',(byte)'S',(byte)'H',                (byte)'=',(byte)'W',(byte)'A','A'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)')',(byte)'S',(byte)'T',                (byte)'=',(byte)'W',(byte)'E','Y'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)')',(byte)'S',                    (byte)'=',(byte)'W',(byte)'A','H'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)')',(byte)'T',                    (byte)'=',(byte)'W',(byte)'A','A'|0x80,
            (byte)'(',(byte)'W',(byte)'H',(byte)'E',(byte)'R',(byte)'E',(byte)')',            (byte)'=',(byte)'W',(byte)'H',(byte)'E',(byte)'H','R'|0x80,
            (byte)'(',(byte)'W',(byte)'H',(byte)'A',(byte)'T',(byte)')',                (byte)'=',(byte)'W',(byte)'H',(byte)'A',(byte)'H','T'|0x80,
            (byte)'(',(byte)'W',(byte)'H',(byte)'O',(byte)'L',(byte)')',                (byte)'=',(byte)'/',(byte)'H',(byte)'O',(byte)'W','L'|0x80,
            (byte)'(',(byte)'W',(byte)'H',(byte)'O',(byte)')',                    (byte)'=',(byte)'/',(byte)'H',(byte)'U','W'|0x80,
            (byte)'(',(byte)'W',(byte)'H',(byte)')',                        (byte)'=',(byte)'W','H'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)'R',(byte)')',(byte)'#',                (byte)'=',(byte)'W',(byte)'E',(byte)'H','R'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)'R',(byte)')',                    (byte)'=',(byte)'W',(byte)'A',(byte)'O','R'|0x80,
            (byte)'(',(byte)'W',(byte)'O',(byte)'R',(byte)')',(byte)'^',                (byte)'=',(byte)'W',(byte)'E','R'|0x80,
            (byte)'(',(byte)'W',(byte)'R',(byte)')',                        (byte)'=','R'|0x80,
            (byte)'(',(byte)'W',(byte)'O',(byte)'M',(byte)')',(byte)'A',                (byte)'=',(byte)'W',(byte)'U',(byte)'H','M'|0x80,
            (byte)'(',(byte)'W',(byte)'O',(byte)'M',(byte)')',(byte)'E',                (byte)'=',(byte)'W',(byte)'I',(byte)'H','M'|0x80,
            (byte)'(',(byte)'W',(byte)'E',(byte)'A',(byte)')',(byte)'R',                (byte)'=',(byte)'W',(byte)'E','H'|0x80,
            (byte)'(',(byte)'W',(byte)'A',(byte)'N',(byte)'T',(byte)')',                (byte)'=',(byte)'W',(byte)'A',(byte)'A',(byte)'5',(byte)'N','T'|0x80,
            (byte)'A',(byte)'N',(byte)'S',(byte)'(',(byte)'W',(byte)'E',(byte)'R',(byte)')',        (byte)'=',(byte)'E','R'|0x80,
            (byte)'(',(byte)'W',(byte)')',                            (byte)'=','W'|0x80,

            (byte)']','X'|0x80,
            (byte)' ',(byte)'(',(byte)'X',(byte)')',(byte)' ',                    (byte)'=',(byte)'E',(byte)'H',(byte)'4',(byte)'K','R'|0x80,
            (byte)' ',(byte)'(',(byte)'X',(byte)')',                        (byte)'=','Z'|0x80,
            (byte)'(',(byte)'X',(byte)')',                            (byte)'=',(byte)'K','S'|0x80,

            (byte)']','Y'|0x80,
            (byte)' ',(byte)'(',(byte)'Y',(byte)')',(byte)' ',                    (byte)'=',(byte)'W',(byte)'A',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'Y',(byte)'O',(byte)'U',(byte)'N',(byte)'G',(byte)')',            (byte)'=',(byte)'Y',(byte)'A',(byte)'H',(byte)'N','X'|0x80,
            (byte)' ',(byte)'(',(byte)'Y',(byte)'O',(byte)'U',(byte)'R',(byte)')',            (byte)'=',(byte)'Y',(byte)'O',(byte)'H','R'|0x80,
            (byte)' ',(byte)'(',(byte)'Y',(byte)'O',(byte)'U',(byte)')',                (byte)'=',(byte)'Y',(byte)'U','W'|0x80,
            (byte)' ',(byte)'(',(byte)'Y',(byte)'E',(byte)'S',(byte)')',                (byte)'=',(byte)'Y',(byte)'E',(byte)'H','S'|0x80,
            (byte)' ',(byte)'(',(byte)'Y',(byte)')',                        (byte)'=','Y'|0x80,
            (byte)'F',(byte)'(',(byte)'Y',(byte)')',                        (byte)'=',(byte)'A','Y'|0x80,
            (byte)'P',(byte)'S',(byte)'(',(byte)'Y',(byte)'C',(byte)'H',(byte)')',            (byte)'=',(byte)'A',(byte)'Y','K'|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'(',(byte)'Y',(byte)')',                (byte)'=',(byte)'I','Y'|0x80,
            (byte)'#',(byte)':',(byte)'^',(byte)'(',(byte)'Y',(byte)')',(byte)'I',            (byte)'=',(byte)'I','Y'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'Y',(byte)')',(byte)' ',                (byte)'=',(byte)'A','Y'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'Y',(byte)')',(byte)'#',                (byte)'=',(byte)'A','Y'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'Y',(byte)')',(byte)'^',(byte)'+',(byte)':',(byte)'#',    (byte)'=',(byte)'I','H'|0x80,
            (byte)' ',(byte)':',(byte)'(',(byte)'Y',(byte)')',(byte)'^',(byte)'#',            (byte)'=',(byte)'A','Y'|0x80,
            (byte)'(',(byte)'Y',(byte)')',                            (byte)'=',(byte)'I','H'|0x80,

            (byte)']','Z'|0x80,
            (byte)' ',(byte)'(',(byte)'Z',(byte)')',(byte)' ',                    (byte)'=',(byte)'Z',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'Z',(byte)')',                            (byte)'=','Z'|0x80,
            'j'|0x80
        };

        public static readonly byte[] rules2 =
        {
            (byte)'(',(byte)'A',(byte)')',                            '='|0x80,
            (byte)'(',(byte)'!',(byte)')',                            (byte)'=','.'|0x80,
            (byte)'(',(byte)'"',(byte)')',(byte)' ',                        (byte)'=',(byte)'-',(byte)'A',(byte)'H',(byte)'5',(byte)'N',(byte)'K',(byte)'W',(byte)'O',(byte)'W',(byte)'T','-'|0x80,
            (byte)'(',(byte)'"',(byte)')',                            (byte)'=',(byte)'K',(byte)'W',(byte)'O',(byte)'W',(byte)'4',(byte)'T','-'|0x80,
            (byte)'(',(byte)'#',(byte)')',                            (byte)'=',(byte)' ',(byte)'N',(byte)'A',(byte)'H',(byte)'4',(byte)'M',(byte)'B',(byte)'E','R'|0x80,
            (byte)'(',(byte)'$',(byte)')',                            (byte)'=',(byte)' ',(byte)'D',(byte)'A',(byte)'A',(byte)'4',(byte)'L',(byte)'E','R'|0x80,
            (byte)'(',(byte)'%',(byte)')',                            (byte)'=',(byte)' ',(byte)'P',(byte)'E',(byte)'R',(byte)'S',(byte)'E',(byte)'H',(byte)'4',(byte)'N','T'|0x80,
            (byte)'(',(byte)'&',(byte)')',                            (byte)'=',(byte)' ',(byte)'A',(byte)'E',(byte)'N','D'|0x80,
            (byte)'(',(byte)'\'',(byte)')',                           '='|0x80,
            (byte)'(',(byte)'*',(byte)')',                            (byte)'=',(byte)' ',(byte)'A',(byte)'E',(byte)'4',(byte)'S',(byte)'T',(byte)'E',(byte)'R',(byte)'I',(byte)'H',(byte)'S','K'|0x80,
            (byte)'(',(byte)'+',(byte)')',                            (byte)'=',(byte)' ',(byte)'P',(byte)'L',(byte)'A',(byte)'H',(byte)'4','S'|0x80,
            (byte)'(',(byte)',',(byte)')',                            (byte)'=',','|0x80,
            (byte)' ',(byte)'(',(byte)'-',(byte)')',(byte)' ',                    (byte)'=','-'|0x80,
            (byte)'(',(byte)'-',(byte)')',                            '='|0x80,
            (byte)'(',(byte)'.',(byte)')',                            (byte)'=',(byte)' ',(byte)'P',(byte)'O',(byte)'Y',(byte)'N','T'|0x80,
            (byte)'(',(byte)'/',(byte)')',                            (byte)'=',(byte)' ',(byte)'S',(byte)'L',(byte)'A',(byte)'E',(byte)'4',(byte)'S','H'|0x80,
            (byte)'(',(byte)'0',(byte)')',                            (byte)'=',(byte)' ',(byte)'Z',(byte)'I',(byte)'Y',(byte)'4',(byte)'R',(byte)'O','W'|0x80,
            (byte)' ',(byte)'(',(byte)'1',(byte)'S',(byte)'T',(byte)')',                (byte)'=',(byte)'F',(byte)'E',(byte)'R',(byte)'4',(byte)'S','T'|0x80,
            (byte)' ',(byte)'(',(byte)'1',(byte)'0',(byte)'T',(byte)'H',(byte)')',            (byte)'=',(byte)'T',(byte)'E',(byte)'H',(byte)'4',(byte)'N',(byte)'T','H'|0x80,
            (byte)'(',(byte)'1',(byte)')',                            (byte)'=',(byte)' ',(byte)'W',(byte)'A',(byte)'H',(byte)'4','N'|0x80,
            (byte)' ',(byte)'(',(byte)'2',(byte)'N',(byte)'D',(byte)')',                (byte)'=',(byte)'S',(byte)'E',(byte)'H',(byte)'4',(byte)'K',(byte)'U',(byte)'N','D'|0x80,
            (byte)'(',(byte)'2',(byte)')',                            (byte)'=',(byte)' ',(byte)'T',(byte)'U',(byte)'W','4'|0x80,
            (byte)' ',(byte)'(',(byte)'3',(byte)'R',(byte)'D',(byte)')',                (byte)'=',(byte)'T',(byte)'H',(byte)'E',(byte)'R',(byte)'4','D'|0x80,
            (byte)'(',(byte)'3',(byte)')',                            (byte)'=',(byte)' ',(byte)'T',(byte)'H',(byte)'R',(byte)'I',(byte)'Y','4'|0x80,
            (byte)'(',(byte)'4',(byte)')',                            (byte)'=',(byte)' ',(byte)'F',(byte)'O',(byte)'H',(byte)'4','R'|0x80,
            (byte)' ',(byte)'(',(byte)'5',(byte)'T',(byte)'H',(byte)')',                (byte)'=',(byte)'F',(byte)'I',(byte)'H',(byte)'4',(byte)'F',(byte)'T','H'|0x80,
            (byte)'(',(byte)'5',(byte)')',                            (byte)'=',(byte)' ',(byte)'F',(byte)'A',(byte)'Y',(byte)'4','V'|0x80,
            (byte)' ',(byte)'(',(byte)'6',(byte)'4',(byte)')',(byte)' ',                (byte)'=',(byte)'S',(byte)'I',(byte)'H',(byte)'4',(byte)'K',(byte)'S',(byte)'T',(byte)'I',(byte)'Y',(byte)' ',(byte)'F',(byte)'O',(byte)'H','R'|0x80,
            (byte)'(',(byte)'6',(byte)')',                            (byte)'=',(byte)' ',(byte)'S',(byte)'I',(byte)'H',(byte)'4',(byte)'K','S'|0x80,
            (byte)'(',(byte)'7',(byte)')',                            (byte)'=',(byte)' ',(byte)'S',(byte)'E',(byte)'H',(byte)'4',(byte)'V',(byte)'U','N'|0x80,
            (byte)' ',(byte)'(',(byte)'8',(byte)'T',(byte)'H',(byte)')',                (byte)'=',(byte)'E',(byte)'Y',(byte)'4',(byte)'T','H'|0x80,
            (byte)'(',(byte)'8',(byte)')',                            (byte)'=',(byte)' ',(byte)'E',(byte)'Y',(byte)'4','T'|0x80,
            (byte)'(',(byte)'9',(byte)')',                            (byte)'=',(byte)' ',(byte)'N',(byte)'A',(byte)'Y',(byte)'4','N'|0x80,
            (byte)'(',(byte)':',(byte)')',                            (byte)'=','.'|0x80,
            (byte)'(',(byte)';',(byte)')',                            (byte)'=','.'|0x80,
            (byte)'(',(byte)'<',(byte)')',                            (byte)'=',(byte)' ',(byte)'L',(byte)'E',(byte)'H',(byte)'4',(byte)'S',(byte)' ',(byte)'D',(byte)'H',(byte)'A',(byte)'E','N'|0x80,
            (byte)'(',(byte)'=',(byte)')',                            (byte)'=',(byte)' ',(byte)'I',(byte)'Y',(byte)'4',(byte)'K',(byte)'W',(byte)'U',(byte)'L','Z'|0x80,
            (byte)'(',(byte)'>',(byte)')',                            (byte)'=',(byte)' ',(byte)'G',(byte)'R',(byte)'E',(byte)'Y',(byte)'4',(byte)'T',(byte)'E',(byte)'R',(byte)' ',(byte)'D',(byte)'H',(byte)'A',(byte)'E','N'|0x80,
            (byte)'(',(byte)'?',(byte)')',                            (byte)'=','?'|0x80,
            (byte)'(',(byte)'@',(byte)')',                            (byte)'=',(byte)' ',(byte)'A',(byte)'E',(byte)'6','T'|0x80,
            (byte)'(',(byte)'^',(byte)')',                            (byte)'=',(byte)' ',(byte)'K',(byte)'A',(byte)'E',(byte)'4',(byte)'R',(byte)'I',(byte)'X','T'|0x80,
            (byte)']','A'|0x80
        };


        //26 items. From 'A' to 'Z'
        // positions for mem62 and mem63 for each character
        public static readonly byte[] tab37489 =
        {
            0, 149, 247, 162, 57, 197, 6, 126,
            199, 38, 55, 78, 145, 241, 85, 161,
            254, 36, 69, 45, 167, 54, 83, 46,
            71, 218
        };

        public static readonly byte[] tab37515 =
        {
            125, 126, 126, 127, 128, 129, 130, 130,
            130, 132, 132, 132, 132, 132, 133, 135,
            135, 136, 136, 137, 138, 139, 139, 140,
            140, 140
        };

    }
}