name: Build and Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
      - name: Build
        run: dotnet build -c Release
      - name: Pack
        run: dotnet pack -c Release -o packages
      - name: Publish to NuGet
        run: dotnet nuget push packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      - name: Publish to Github Packages
        run: dotnet nuget push packages/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" api-key ${{ secrets.GH_PAT }}
      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nugetpackage
          path: packages
